#!/usr/bin/env bash
set -ex

rm -rf out/ClrBridge.gen.cs out/ClrBridge.dll
mkdir -p out

rund -g -debug -I=dlib dotnetlib/generateClrBridge.d > out/ClrBridge.gen.cs
csc /out:out/ClrBridge.dll /t:library dotnetlib/ClrBridge.cs out/ClrBridge.gen.cs
